version: '3.8'

services:
  # Backend API service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: economix-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - economix-network

  # Frontend service (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: economix-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api
    depends_on:
      - app
    networks:
      - economix-network

  # MySQL database service
  db:
    image: mysql:8
    container_name: economix-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: economix
      MYSQL_USER: economix_user
      MYSQL_PASSWORD: economix_password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - economix-network

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: economix-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - economix-network

volumes:
  mysql-data:

networks:
  economix-network:
    driver: bridge
